spring:
  application:
    name: synergy cooperative
  datasource:
    url: jdbc:postgresql://localhost:5432/synergy_cooperative
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    dbcp2:
      max-wait-millis: 30000
      validation-query: select 1
      validation-query-timeout: 30
  mail:
    host: smtp.gmail.com
    username: example@gmail.com
    password: example
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
springdoc:
  pathsToMatch: /api/**

server:
  port: 8000

authentication:
  auth:
    accessTokenCookieName: SESSIONID
    refreshTokenCookieName: REFRESHID
  details:
    secret: secret-key

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.glassfish.jersey: ERROR
    org.reflections: ERROR
    com.synergy.synergy_cooperative.authorization: INFO
    org.apache.tomcat.util.http.parser.Cookie: DEBUG