spring:
  application:
    name: synergy cooperative
  datasource:
    url: jdbc:postgresql://localhost:5432/synergy_cooperative
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: rotimi
    dbcp2:
      max-wait-millis: 30000
      validation-query: select 1
      validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
springdoc:
  pathsToMatch: /api/**

server:
  port: 8500

authentication-test:
  auth:
    accessTokenCookieName: SESSIONID

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.glassfish.jersey: ERROR
    org.reflections: ERROR
    com.synergy.synergy_cooperative.authorization: INFO